spring:
  application:
    name: discovery-service
  config:
    import: optional:configserver:http://localhost:8888
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
#don't override port from config server - best way to use it config server only
server:
  port: 8761